USE `destini_numbers`;

INSERT INTO `products` (`name`, `category`, `price`, `description`, `image_path`, `stock`) VALUES
  ('Moonstone', 'Crystal', 0.00, 'Used for emotional balance, intuition support, and calm decision energy.', 'assets/img/moonstone.svg', 0),
  ('Green Aventurine', 'Crystal', 0.00, 'Recommended for opportunity flow, confidence, and growth-focused goals.', 'assets/img/green-aventurine.svg', 0),
  ('Pyrite', 'Crystal', 0.00, 'Often chosen for business and money mindset reinforcement.', 'assets/img/pyrite.svg', 0),
  ('Amethyst', 'Crystal', 0.00, 'Supports focus, mind calmness, and spiritual grounding.', 'assets/img/amethyst.svg', 0),
  ('Black Tourmaline', 'Crystal', 0.00, 'Protection-focused stone for energetic boundary support.', 'assets/img/black-tourmaline.svg', 0),
  ('Blue Lace Agate', 'Crystal', 0.00, 'Communication and emotional softness support for relationship clarity.', 'assets/img/blue-lace-agate.svg', 0),
  ('Lapis Lazuli', 'Crystal', 0.00, 'Awareness and strategic clarity support for leadership decisions.', 'assets/img/lapis-lazuli.svg', 0),
  ('Sunstone', 'Crystal', 0.00, 'Vitality and confidence support for action and motivation.', 'assets/img/sunstone.svg', 0),
  ('Rose Quartz', 'Crystal', 0.00, 'Relationship healing and emotional comfort support.', 'assets/img/rose-quartz.svg', 0),
  ('Rudraksha 1 Mukhi to 14 Mukhi', 'Rudraksha', 0.00, 'Guided selection based on chart and numerology profile with usage guidance.', 'assets/img/rudraksha-1-14.svg', 0),
  ('Emerald, Ruby, Topaz', 'Gemstone', 0.00, 'High-demand gemstone range for business, career, and communication support.', 'assets/img/emerald-ruby-topaz.svg', 0),
  ('Amethyst, Moonga, Pearl', 'Gemstone', 0.00, 'Remedy-centered gemstones with wear guidance and purpose-specific selection support.', 'assets/img/amethyst-moonga-pearl.svg', 0),
  ('Navratri Puja Kit', 'Kit', 0.00, 'Complete puja box kit with essential samagri for Navratri rituals.', 'assets/img/navratri-kit.svg', 0),
  ('Hanuman Puja Kit', 'Kit', 0.00, 'Structured kit with required materials for Hanuman puja process.', 'assets/img/hanuman-kit.svg', 0),
  ('Individual Puja Items', 'Samagri', 0.00, 'Single puja items and samagri available based on requirement list.', 'assets/img/puja-samagri.svg', 0);

INSERT INTO `services` (`title`, `duration`, `price`, `description`) VALUES
  ('Complete Numerology Report', 'Custom', 0.00, 'Full reading of life path, destiny, soul urge, and name energy with practical action roadmap.'),
  ('Business Numerology', 'Custom', 0.00, 'Business name vibration analysis, timing alignment, and founder-number compatibility assessment.'),
  ('Name Correction', 'Custom', 0.00, 'Name optimization for adults and newborn naming suggestions with numerology alignment.'),
  ('Lucky Number Mapping', 'Custom', 0.00, 'Lucky numbers for vehicle, house, and mobile selection based on personal chart.'),
  ('Remedies and Solutions', 'Custom', 0.00, 'Simple, easy-to-implement remedies designed around current challenge and timeline.'),
  ('Future Forecasting', 'Custom', 0.00, 'Upcoming period analysis for better timing in major personal and professional decisions.'),
  ('Health Consultation', 'Custom', 0.00, 'Planetary period review for health sensitivity and preventive routine planning.'),
  ('Relationship and Marriage Guidance', 'Custom', 0.00, 'Kundali matching, compatibility insight, and practical alignment strategies for marriage decisions.'),
  ('Career Direction', 'Custom', 0.00, 'Role fit, timing for change, and growth windows mapped from chart and number systems.'),
  ('Money and Financial Analysis', 'Custom', 0.00, 'Income pattern analysis, financial cycle timing, and risk-control guidance.'),
  ('Legal and Court Case Remedies', 'Custom', 0.00, 'Astro-remedial support to strengthen confidence and timing in legal matters.'),
  ('Crystal and Gem Remedies', 'Custom', 0.00, 'Gemstone and crystal recommendation based on chart factors and goals.'),
  ('Custom Crystal Bracelets', 'Custom', 0.00, 'Goal-specific bracelets prepared for health, relationship, career, and money support.'),
  ('Personalized Crystal Combinations', 'Custom', 0.00, 'Custom crystal pairings based on chart, number profile, and present life goals.'),
  ('Rudraksha Recommendation', 'Custom', 0.00, 'Selection support from 1 Mukhi to 14 Mukhi based on energetic requirement.'),
  ('Career Alignment Session', '1 hour', 2500.00, 'Life path, chart alignment, and career strategy for professionals and students.'),
  ('Business Numerology Session', '1.5 hours', 3500.00, 'Business naming and timing strategy for founders, startups, and rebranding plans.'),
  ('Personal Destiny Reading', '1 hour', 2500.00, 'Psychic, destiny, and name number mapping with corrective roadmap.'),
  ('Full Transformation Package', 'Custom', 9000.00, 'Name correction, chart reading, career counseling, and 3-month follow-up support.'),
  ('Business Scaling Intensive', 'Custom', 12000.00, 'Complete founder and business alignment with 6-week implementation follow-up.'),
  ('Family Alignment Package', 'Custom', 8000.00, 'Parent readings, partner compatibility, and child life path planning.');
